### ISSUE TITLE
Ailleurs

### ISSUE THREAD

**Issue by SylvainCLS** [terresolide/geodesy-plotter-vjs#21]
**J'ai un peu circulé ailleurs que sous visualization-gnss:**
Sur le texte présentant le pôle formater, je me demande s'il ne faut pas aussi mentionner GGOS (au niveau de l'IUGG) qui donne 
des liens plus rapides vers les services d'observations internationaux... ou de lister ces services au niveau du point 4. des "fonctions". 

Onglet "Données et Services" / "Découverte et accès aux données" 

La liste actuelles ~80 fiches parait déjà pléthorique. Il est  possible de limiter les affichages via le bandeau de gauche 
mais je me demande si une présentation initiale sous forme de plan serait pas plus pratique dans la phase de découverte
(que l'affichage direct de toutes les fiches). Par exemple il existe 20 fiches nommés "Collection d'interférogrammes et série temporelles Sentinel-1" qui ne diffèrent que pour la zone géographique...
Je ne vois pas encore de fiche sur les séries de position GNSS.... 

Creation de compte et login : pas de pb particulier. 
La charte d'accès aux services envoie vers une erreur "404 / It looks like nothing was found at this location. Maybe try one of the links below or a search?"

J'ai fais une demande d'accès au service pour les produits " GDM-OPT-ETQ" vers 17h42 heure locale/Toulouse et une fenêtre m'a dit 
qu'un mail m'avait été envoyé : rien reçu !

**Comment by epointal** [comment]
- Le pb de la charte a bien été identifié, il manque la mise à jour... (Pb passage de monolingue à bilingue...)
- Pour les fiches GNSS, elles n'ont pas été créées. Sans doute bientôt.
- De notre côté la demande d'accès à GDM-OPT-ETQ a bien été enregistré. Je n'ai pas eu de retour "Undelivered mail".

**Comment by RaphaelGrandin** [comment]
Merci @SylvainCLS, on prend note de tous ces commentaires qui concernant les pages ForM@Ter en général (mais pas la plateforme). C'est très utile, merci.

**Comment by epointal** [comment]
[x] service de calcul à la demande - erreur 404 vers charte résolue (depuis longtemps mais tout juste mis à jour)
