### ISSUE TITLE
Appel à idées pour le nom de la plateforme

### ISSUE THREAD

**Issue by RaphaelGrandin** [terresolide/geodesy-plotter-vjs#40]
Il faut trouver un nom à cette plateforme.

On doit pouvoir faire mieux que "Service de visualisation GNSS ForM@Ter".

Utilisez ce ticket pour faire des propositions!

**Comment by RaphaelGrandin** [comment]
Je me lance: Landmove, Gravitude, Terranet, GeoPivot, EarthPosMap, Geovizy, Geodash...

**Comment by deprezal** [comment]
VizM@ter

**Comment by EmilieKlein** [comment]
J'aime bien 'EarthPosMap' !
Pas trop d'inspiration, par contre, je me demande s'il ne faudrait pas garder 'ForM@Ter' dans le nom - pour continuer d'identifier d'ou ca vient  ? Le NGL n'a pas de nom spécifique pour son service de visu, mais 'Nevada Geodetic Lab' apparait bien partout donc ca reste en tete..

**Comment by mvergnolle** [comment]
Je pense qu'il faut éviter : 
- de mettre "GNSS" dans le nom de la plateforme (cf commentaire Marianne, d'autres types de series pourraient y être visualisée - ex : surcharge issues de modèle, dérivées d'autres types de mesure, inSAR, ...)
- de mettre "position" dans le nom de la plateforme (même raison, série de paramètre troposphérique, ionosphérique, ...)

Dans l'idée de garder le lien avec le nom "ForM@Ter", j'aime bien le VizM@ter ;-)

**Comment by lrolland06** [comment]
ou EarthFormView

**Comment by RaphaelGrandin** [comment]
Reticula (du latin, retis, "filet, réseau")

**Comment by RaphaelGrandin** [comment]
GeodeViz, GeodViz

**Comment by SylvainCLS** [comment]
The Geod Plotter                           (mix de la proposition d'Alvaro avec Geod)
