### ISSUE TITLE
SARI

### ISSUE THREAD

**Issue by alvarosantamariagomez** [terresolide/geodesy-plotter-vjs#41]
Si vous avez des commentaires ou suggestions concernant l'intégration de SARI dans ForM@Ter, vous êtes au bon endroit.

Si vous avez des commentaires ou suggestions concernant le fonctionnement de SARI, vous pouvez faire un ticket ici :  
[github SARI](https://github.com/alvarosantamariagomez/sari)

**Comment by lrolland06** [comment]
Peut-on avoir à terme SARI installé au même "endroit" que les séries (ie sur les serveurs Form@ter) ?

**Comment by alvarosantamariagomez** [comment]
Si le serveur web ForM@Ter a aussi les capacités d'un serveur de calcul (mémoire, cpu et nombre de processeurs) en quantité suffisante pour fair tourner les deux services en simultané, alors oui, en théorie, c'est possible.  
En pratique, il y a plusieurs façons de metre ça en œuvre, mais c'est du terrain inconnu pour moi.  

Puisque SARI est aussi mis à disposition dans son propre [conteneur Docker](https://hub.docker.com/r/alvarosg/sari#!), le plus simple (et certainemen le moins cher) à mon avis est peut-être de passer par un orchestrateur de conteneurs comme [kubernetes](https://kubernetes.io/).  
Ça reste un solution fait maison, donc à voir si l'on gagne en temps d'execution par rapport à la solution actuelle sur le serveur Shinyapps.

**Comment by epointal** [comment]
Je vais en discuter avec le service informatique.

**Comment by alvarosantamariagomez** [comment]
Est-ce possible de mettre le lien SARI avec une autre couleur ou le séparer du bouton de téléchargement ou une autre idée pour laisser plus clair qu'il s'aggit de deux actions différentes ?

**Comment by alvarosantamariagomez** [comment]
Ajouter le lien SARI dans la liste des ressources/outils ForM@Ter

**Comment by epointal** [comment]
C'est fait je crois
