### ISSUE TITLE
crédits données réseau ORPHEON

### ISSUE THREAD

**Issue by mmetois** [terresolide/geodesy-plotter-vjs#67]
Bonjour, 
Les données du réseau privé Orphéon dont Rénag est partenaire sont traitées par plusieurs groupes de recherche et c'est super. Elles apparaissent notamment dans la solution SPOTGINS sur le geodesy plotter, mais aucune information de type crédit n'est indiqué pour les stations concernées, et le réseau Orphéon n'apparait pas. 
Nous allons travailler cette année à rentrer les métadonnées des stations Orphéon dans M3G ce qui devrait rendre la tâche automatique. En attendant, est il possible pour le lancement officiel d'insérer un crédit quelque part ? 
Soit indiquer dans les informations des stations concernées la phrase : ORPHEON GNSS data were provided to the authors for a scientific use in the framework of the GEODATA-CNRS-INSU AGREEMENT
Soit indiquer cette phrase dans les références associées à la description de la solution SPOTGINS : ORPHEON GNSS data were provided to the authors for a scientific use in the framework of the GEODATA-CNRS-INSU AGREEMENT
et idéalement rattacher les stations indiquées dans le fichier joint comme appartenant au réseau Orphéon ? 

Merci, 
Marianne
[Orpheon_Geodata_20230912.csv](https://github.com/terresolide/geodesy-plotter-vjs/files/12594532/Orpheon_Geodata_20230912.csv)

**Comment by epointal** [comment]
Je regarde:
 Rattacher les stations au réseau ORPHEON, ne me semble pas trop compliqué.
Je peux afficher  la phrase à l'arrache "ORPHEON GNSS data were provided to the authors for a scientific use in the framework of the GEODATA-CNRS-INSU AGREEMENT" quand la station fait partie du réseau **en attendant mieux**.
Je ne pourrai le mettre à jour que mardi, si jamais j'ai le temps de faire ces maj.

**Comment by epointal** [comment]
Sinon, je reçois les notifications sur mon compte gmail que je regarde assez peu.

**Comment by alvarosantamariagomez** [comment]
@mmetois je viens de voir que la station BLGU00ESP se trouve dans le fichier csv mais elle n'est pas une station ORPHEON.
Liste à vérifier ? Je n'ai pas vérifié s'il y a d'autres stations
@epointal il faudrait enlever le label ORPHEON de cette station.

**Comment by mmetois** [comment]
ok, je vois que c'est une station IGS, il faut être sûrs que c'est la même et ça ne vaut surement pas le coup de rinexer à partir du RTK les stations IGS utilisées par Orphéon... donc c'est un problème plus général, il va falloir qu'on en cause avec Maurin et Lucie

**Comment by alvarosantamariagomez** [comment]
C'est une station ERGNSS (IGN Espagne) et EPOS aussi, pas IGS il me semble.
Il y a peut-être un doublon quelque part en France (je n'ai pas trouvé), mais en tout cas les rinex v2 distribués par le RENAG sont bien de cette station espagnole. Sinon il y a les rinex v3 chez l'IGN Espagne.

**Comment by alvarosantamariagomez** [comment]
je me demande comment elle a été faite cette liste ORPHEON, car c'est possible que les données temps-réel de BLGU00ESP sont utilisées par ORPHEON, mais cela ne fait pas d'elle une station avec label ORPHEON

**Comment by mmetois** [comment]
elle a été faite avec les données envoyées par Orphéon sur le ftp rénag et qui sont rinexées au data center je pense. Et oui, c'est sur qu'Orphéon intègre les stations d'autres réseaux. J'ai envoyé un mail au DC pour qu'on remette tout ça à plat. Ca va de toute façon être fait au moment où les stations Orphéon vont être rentrées dans le M3G...
